require("dotenv").config();
const env = process.env;

module.exports = {
  PORT: env.PORT,
  MONGO_CONNECT_URL: env.MONGO_CONNECT_URL,
  JWT_ACCESS_SECRET: env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET,
  WEB3_HTTP: env.WEB3_HTTP,
  SIGN_MESSAGE: env.SIGN_MESSAGE,
  OPENSEA_KEY: env.OPENSEA_KEY,
  JWT_ACCESS_SECRET: env.JWT_ACCESS_SECRET,
  JWT_REFRESH_SECRET: env.JWT_REFRESH_SECRET,
  ACCESS_TOKEN_TIME: env.ACCESS_TOKEN_TIME,
  REFRESH_TOKEN_TIME: env.REFRESH_TOKEN_TIME,
  COOKIE_DAYS: env.COOKIE_DAYS,
};
